### ISSUE TITLE
Supported Virtualization Software

### ISSUE THREAD

**Issue by locovich** [sh4hin/Androl4b#15]
The VM image seems to be exported as OVA 2, which VMware Player 14 does not support.
I tried a work around, by importing on VirtualBox, and then exporting as OVA 1.0, that VMware takes. But still, the VM does not start correctly. Not sure if this is an issue with the version or in my env. In any case, I'd suggest to add a note in the readme stating that the VM is for use on VirtualBox only if that's the case.

**Comment by sh4hin** [comment]
Thanks for the feedback, i will fix the issue.
