### ISSUE TITLE
integrity of files failed - md5sum: WHY?

### ISSUE THREAD

**Issue by AjaxFB** [sh4hin/Androl4b#8]
MD5SUM
6710c2b1f583644a8b03e4301d13cc1c  Androl4b.ova.7z
3e8c42edc0b336325f8a5dd2d45549b3  Androl4b.ova.7z.001
0d9a3bfadb122f357bfa274853ce2592  Androl4b.ova.7z.002

I am use cat to merge files, but this had damaged.

Please a help.

**Comment by AjaxFB** [comment]
I change the order, no matter.

dd7f825a386a8f04e0b72135e5b048e5  Androl4b.ova.7z

**Comment by sh4hin** [comment]
@AjaxFB I have added Google drive links and it is working for me, Could you try those links?

**Comment by AjaxFB** [comment]
b1b469af88a80e8da10996bb6616a70e  Androl4b.ova.7z.002
waiting 001...

**Comment by AjaxFB** [comment]
f3cef2dc6a2f72740f636c9768e4a90b  Androl4b.ova.7z.001

**Comment by AjaxFB** [comment]
running  cat Androl4b.ova.7z.001 Androl4b.ova.7z.002 > /mnt/g/Androl4b.ova.7z

**Comment by AjaxFB** [comment]
eb9f90efac167a443135244921fbc693  /mnt/g/Androl4b.ova.7z
testing import ova

**Comment by AjaxFB** [comment]
FAIL! ~~


Implementation of the USB 2.0 controller not found!
Because the USB 2.0 controller state is part of the saved VM state, the VM cannot be started. To fix this problem, either install the 'Oracle VM VirtualBox Extension Pack' or disable USB 2.0 support in the VM settings.
Note! This error could also mean that an incompatible version of the 'Oracle VM VirtualBox Extension Pack' is installed (VERR_NOT_FOUND).

Código de Resultado: 
E_FAIL (0x80004005)
Componente: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by AjaxFB** [comment]
https://ibb.co/kVFvmG thanks

**Comment by AjaxFB** [comment]
fb4fd9f3f14260bb458f795f7a442629  Androl4b.ova
